services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: files
      POSTGRES_PASSWORD: files
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/model.sql:/docker-entrypoint-initdb.d/01_model.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U files -d filesdb"]
      interval: 10s
      retries: 3
    ports: ["5432:5432"]

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://files:files@db:5432/filesdb
    ports: ["8000:8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/health || exit 1"]
      interval: 10s
      retries: 3
volumes:
  pgdata:
